name: 'Tinybird Stats Push'
description: 'Send job statistics to Tinybird'
author: 'silv-io'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'rocket'
  color: 'teal'

# Define your inputs here.
inputs:
  tinybird_token:
    description: 'The token to authenticate with Tinybird'
    required: true
  tinybird_endpoint:
    description: 'The endpoint to send the data to'
    required: true

runs:
  using: node20
  main: main/index.js
  post: post/index.js
